### ISSUE TITLE
[CSS] buttoning

### ISSUE THREAD

**Issue by corbeau217** [corbeau217/corbeau217.github.io#14]
* give buttons inset border to mock shadows when youreusing them

**Comment by corbeau217** [comment]
somewhat virtual-backburnered, should have a task group

**Comment by corbeau217** [comment]
is this just the hover/active includes:

```css
border-bottom-style: inset;
border-left-style: inset;
border-bottom-weight: ${text-shadow-y};
border-left-weight: ${text-shadow-x};
```

bc then that's done vry quick
